### ISSUE TITLE
[backstage-plugin-flux] Getting Unauthorized in Backstage : 401

### ISSUE THREAD

**Issue by iamsourabh-in** [weaveworks/weaveworks-backstage#52]
I am new to backstage, but i am able to authenticate myself and get Kubernetes resource, using `service Account Token`.

But when using Flux plugin, I am getting the below, Error.
`
Request failed with 401 Unauthorized, {"error":{"name":"AuthenticationError","message":"No Backstage token","stack":"AuthenticationError: No Backstage token\n at getEntityByReq
`

**Comment by bigkevmcd** [comment]
@iamsourabh-in I'm fairly sure that this is the same as #50 which is an upstream issue, I've added a note to the README which highlights this.

**Comment by bigkevmcd** [comment]
@iamsourabh-in I'm going to close this issue, if or when guest tokens are available upstream (in Backstage) if we need to do something we'll do it at that point
