### ISSUE TITLE
[flux-runtime] Show if a new version of flux is available

### ISSUE THREAD

**Issue by foot** [weaveworks/weaveworks-backstage#56]
Probably checking github-releases

There might a backstage-github-* plugin with examples of querying the github releases api w/ a token etc.

- Docs in the plugin guide, how to setup the BS proxy for the github api endpoint
- Hit it and parse out latest version
- Compare against versions in table
- Add a new column "Update available" button / link / that links out to github releases page

**Comment by bigkevmcd** [comment]
```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/fluxcd/flux2/releases/latest
```

**Comment by foot** [comment]
The other way to would be to explore doing github requests straight from the browser and using BS's [`githubAuthApi`](https://backstage.io/docs/reference/core-plugin-api.githubauthapiref/)

https://github.com/backstage/backstage/blob/master/plugins/git-release-manager/src/api/GitReleaseClient.ts#L181-L197

https://github.com/backstage/backstage/blob/master/plugins/git-release-manager/src/api/GitReleaseClient.ts#L87

I'm not sure how this works in practice, if it would pop up a "please auth with github" dialog when you visit that page etc.. 

You might still be able to do unauth'd github requests via the FE w/out a proxy? Not 100%..
