### ISSUE TITLE
Backstage cannot be upgraded due flux plugin dependencies not met

### ISSUE THREAD

**Issue by ferrandinand** [weaveworks/weaveworks-backstage#60]
I tried to upgrade backstage following the user guide:
https://backstage.io/docs/getting-started/keeping-backstage-updated/

```
yarn backstage-cli versions:check --fix
yarn run v1.22.19

The following packages must be deduplicated by updating dependencies in package.json

 @backstage/plugin-kubernetes **@ ^0.10.2 should be changed to ^0.11.2**

```

The following packages can be deduplicated by updating dependencies in package.json

```
  @backstage/plugin-kubernetes-common @ ^0.6.5 should be changed to ^0.7.1
  @backstage/plugin-kubernetes-common @ ^0.6.6 should be changed to ^0.7.1
```

For now running to make it work
`yarn backstage-cli versions:bump --pattern '@{weaveworksoss}/*'`

**Comment by bigkevmcd** [comment]
@ferrandinand Thanks, we'll get our dependencies bumped.

**Comment by bigkevmcd** [comment]
@ferrandinand I've just tagged v0.8.5 which should fix this.
