### ISSUE TITLE
Error sorting resources by data

### ISSUE THREAD

**Issue by ferrandinand** [weaveworks/weaveworks-backstage#68]
There is a small issue trying to sort resources by Updated date it uses the textual output instead of the raw date value.

See the image attached 
![flux-plugin](https://github.com/weaveworks/weaveworks-backstage/assets/8616135/89cf6e03-2cfe-4eb1-8f37-9a77e7377966)

**Comment by bigkevmcd** [comment]
@ferrandinand Thanks for reporting this, we'll get a release out with the fix early in the new year.
